# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Bo Peng
tagline:             2A Software Engineering, University of Waterloo
url:                 bopeng.io
paginate:            4
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Bo Peng
  url:               bopeng.io
  email:             me@bopeng.io

# Custom vars
version:             1.0.0
github:              pobeng
  repo:              https://github.com/pobeng/pobeng.github.io

# Top nav bar
pages_list:
  About: '/about'
  Blog: '/blog'
  Contact: '/contact'
